---
- hosts: controllers
  roles:
  - common_openstack_node
  - mariadb
  - rabbitmq
  - memcached
  - keystone
  - glance
  - nova-controller
  - neutron-controller
  - horizon
- hosts: computes
  roles:
  - common_openstack_node
  - nova-compute
  - neutron-compute
