---
- hosts: controllers
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - common_openstack_node
  - mariadb
  - rabbitmq
  - memcached
  - keystone
  - glance
  - nova-controller
  - neutron-controller
  - horizon
- hosts: computes
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - common_openstack_node
  - nova-compute
  - neutron-compute
