---
- name: Install Neutron on computes
  apt:
    name: neutron-linuxbridge-agent
    update_cache: yes
- name: Configure Neutron on computes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/neutron/{{ item }}'
  with_items:
    - neutron.conf
    - plugins/ml2/linuxbridge_agent.ini
- name: Configure nova-compute to use Neutron
  ini_file:
    dest: /etc/nova/nova.conf
    section: neutron
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items:
    - { key: 'url', value: 'http://10.10.1.11:9696'}
    - { key: 'auth_url', value: 'http://10.10.1.11:35357'}
    - { key: 'auth_type', value: 'password'}
    - { key: 'project_domain_name', value: 'default'}
    - { key: 'user_domain_name', value: 'default'}
    - { key: 'region_name', value: 'RegionOne'}
    - { key: 'project_name', value: 'service'}
    - { key: 'username', value: 'neutron'}
    - { key: 'password', value: 'neutron'}
- name: Restart nova-compute service after configuration for neutron usage
  service:
    name: nova-compute
    state: restarted
- name: Restart neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    state: restarted
