---
- name: Install required packages
  apt:
    name:
      - software-properties-common
      - python-mysqldb
      - python-pip
    update_cache: yes
- name: Add OpenStack repository
  shell: "add-apt-repository -y cloud-archive:ocata"
- name: Install OpenStack client
  pip:
    name:
      - pip
      - python-openstackclient
  extra_args: --upgrade
