---
- name: sudo
- name: Install required packages
  apt:
    name:
      - software-properties-common
      - python-mysqldb
    update_cache: yes
- name: Add OpenStack repository
  shell: "add-apt-repository -y cloud-archive:ocata"
- name: Install OpenStack client
  apt:
    name:
      - python-openstackclient
