---
- name: Install software-properties-common package
  apt:
    name:
      - software-properties-common
    update_cache: yes
- name: Add OpenStack repository
  shell: "add-apt-repository -y cloud-archive:ocata"
- name: Install common packages including OpenStack client
  apt:
    name:
      - python-openstackclient
      - python-mysqldb
      - python-pip
    update_cache: yes
