---
- name: Install Horizon
  apt:
    name: openstack-dashboard
    update_cache: yes
- name: Configure Horizon
  template:
    src: openstack-dashboard/local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py
- name: Workaround for https://bugs.launchpad.net/openstack-manuals/+bug/1683594
  file:
    path: /var/lib/openstack-dashboard/secret_key
    owner: www-data
    group: www-data
- name: Reload Apache2 service
  service:
    name: apache2
    state: reloaded
